/**
 * Heaven Songs — DEMO DATA.
 *
 * These are ORIGINAL placeholder progressions written for Heaven Synth.
 * They are not transcriptions of commercial recordings. A verified catalog
 * can be added later by dropping more `Song[]` files into the catalog.
 */

import type { Song } from "./types";

const s = (name: string, degrees: number[], beatsPerChord = 4) => ({
  id: name.toLowerCase().replace(/\s+/g, "-"),
  name,
  degrees,
  beatsPerChord,
});

export const DEMO_SONGS: Song[] = [
  {
    id: "demo-first-light",
    title: "First Light",
    artist: "Heaven Demo",
    keyPc: 7,
    scale: "major",
    bpm: 96,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Pop",
    origin: "demo",
    sections: [s("Intro", [1, 5, 6, 4]), s("Verse", [1, 5, 6, 4]), s("Chorus", [4, 1, 5, 6])],
  },
  {
    id: "demo-cloud-runner",
    title: "Cloud Runner",
    artist: "Heaven Demo",
    keyPc: 0,
    scale: "major",
    bpm: 110,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Pop",
    origin: "demo",
    sections: [s("Verse", [1, 4, 5, 5]), s("Chorus", [6, 4, 1, 5])],
  },
  {
    id: "demo-night-tide",
    title: "Night Tide",
    artist: "Heaven Demo",
    keyPc: 9,
    scale: "minor",
    bpm: 84,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Ambient",
    origin: "demo",
    sections: [s("Intro", [1, 6, 3, 7]), s("Verse", [1, 6, 3, 7]), s("Chorus", [4, 5, 1, 1])],
  },
  {
    id: "demo-seven-doors",
    title: "Seven Doors",
    artist: "Heaven Demo",
    keyPc: 2,
    scale: "dorian",
    bpm: 100,
    timeSignature: [4, 4],
    difficulty: "medium",
    genre: "Cinematic",
    origin: "demo",
    sections: [
      s("Intro", [1, 4]),
      s("Verse", [1, 4, 6, 5]),
      s("Pre-Chorus", [2, 5, 1, 6]),
      s("Chorus", [1, 5, 4, 6, 2, 7]),
    ],
  },
  {
    id: "demo-golden-hour",
    title: "Golden Hour",
    artist: "Heaven Demo",
    keyPc: 5,
    scale: "major",
    bpm: 92,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Soul",
    origin: "demo",
    sections: [s("Verse", [1, 6, 2, 5]), s("Chorus", [4, 5, 1, 6])],
  },
  {
    id: "demo-sky-ladder",
    title: "Sky Ladder",
    artist: "Heaven Demo",
    keyPc: 4,
    scale: "minor",
    bpm: 128,
    timeSignature: [4, 4],
    difficulty: "medium",
    genre: "Electronic",
    origin: "demo",
    sections: [
      s("Intro", [1, 1, 6, 6], 2),
      s("Verse", [1, 6, 7, 4], 2),
      s("Chorus", [6, 7, 1, 5, 4, 3], 2),
    ],
  },
  {
    id: "demo-slow-comet",
    title: "Slow Comet",
    artist: "Heaven Demo",
    keyPc: 10,
    scale: "mixolydian",
    bpm: 78,
    timeSignature: [4, 4],
    difficulty: "medium",
    genre: "Blues",
    origin: "demo",
    sections: [s("Verse", [1, 7, 4, 1]), s("Chorus", [4, 4, 1, 5])],
  },
  {
    id: "demo-white-cathedral",
    title: "White Cathedral",
    artist: "Heaven Demo",
    keyPc: 3,
    scale: "major",
    bpm: 70,
    timeSignature: [3, 4],
    difficulty: "medium",
    genre: "Sacred",
    origin: "demo",
    sections: [s("Intro", [1, 3, 6], 3), s("Verse", [1, 5, 6, 4, 2, 5], 3), s("Outro", [1, 4, 1], 3)],
  },
  {
    id: "demo-paper-moon",
    title: "Paper Moon",
    artist: "Heaven Demo",
    keyPc: 8,
    scale: "minor",
    bpm: 104,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Pop",
    origin: "demo",
    sections: [s("Verse", [1, 4, 6, 5]), s("Chorus", [6, 5, 4, 1])],
  },
  {
    id: "demo-glass-river",
    title: "Glass River",
    artist: "Heaven Demo",
    keyPc: 1,
    scale: "dorian",
    bpm: 88,
    timeSignature: [4, 4],
    difficulty: "hard",
    genre: "Jazz",
    origin: "demo",
    sections: [
      s("Verse", [2, 5, 1, 4, 7, 3, 6, 2]),
      s("Bridge", [4, 7, 3, 6]),
      s("Chorus", [1, 6, 2, 5, 3, 4]),
    ],
  },
  {
    id: "demo-morning-bells",
    title: "Morning Bells",
    artist: "Heaven Demo",
    keyPc: 7,
    scale: "major",
    bpm: 118,
    timeSignature: [4, 4],
    difficulty: "easy",
    genre: "Folk",
    origin: "demo",
    sections: [s("Verse", [1, 4, 1, 5]), s("Chorus", [1, 5, 4, 4])],
  },
  {
    id: "demo-ether-drift",
    title: "Ether Drift",
    artist: "Heaven Demo",
    keyPc: 11,
    scale: "minor",
    bpm: 132,
    timeSignature: [4, 4],
    difficulty: "hard",
    genre: "Electronic",
    origin: "demo",
    sections: [
      s("Intro", [1, 7], 2),
      s("Verse", [1, 7, 6, 5, 4, 3], 2),
      s("Pre-Chorus", [4, 5, 6, 7], 2),
      s("Chorus", [1, 5, 6, 4, 2, 7], 2),
      s("Outro", [1, 1], 4),
    ],
  },
];
