/**
 * Heaven Synth — diatonic harmony.
 * Layer: Music Theory Engine.
 *
 * Chords are never stored in tables: every chord is generated by stacking
 * diatonic thirds over the selected scale, so any root/mode combination works.
 */

import { noteLabel, noteToFrequency, pitchClassName } from "./pitch";
import { degreeToSemitones, scaleDegreeNames } from "./scales";

export const KEYS = [
  "C",
  "C#",
  "D",
  "D#",
  "E",
  "F",
  "F#",
  "G",
  "G#",
  "A",
  "A#",
  "B",
] as const;
export type KeyName = (typeof KEYS)[number];

export const ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII"];

export type ModeId = "major" | "minor" | "dorian" | "mixolydian";

export const MODES: { id: ModeId; name: string; steps: number[] }[] = [
  { id: "major", name: "Major", steps: [0, 2, 4, 5, 7, 9, 11] },
  { id: "minor", name: "Minor", steps: [0, 2, 3, 5, 7, 8, 10] },
  { id: "dorian", name: "Dorian", steps: [0, 2, 3, 5, 7, 9, 10] },
  { id: "mixolydian", name: "Mixolydian", steps: [0, 2, 4, 5, 7, 9, 10] },
];

export type Tonality = "auto" | "major" | "minor";
export type VoicingId = "triad" | "inv1" | "inv2" | "seventh" | "open";

export const VOICINGS: { id: VoicingId; name: string }[] = [
  { id: "triad", name: "Triade" },
  { id: "inv1", name: "1° rivolto" },
  { id: "inv2", name: "2° rivolto" },
  { id: "seventh", name: "Settima" },
  { id: "open", name: "Aperto" },
];

export type ChordQuality = "major" | "minor" | "dim" | "aug" | "sus";

export type Chord = {
  /** 0-based scale degree the chord is built on */
  degree: number;
  rootMidi: number;
  rootName: string;
  quality: ChordQuality;
  seventh: boolean;
  /** ascending MIDI notes */
  notes: number[];
  label: string;
};

export type ChordRequest = {
  rootPc: number;
  mode: ModeId;
  degree: number;
  tonality: Tonality;
  voicing: VoicingId;
  octave?: number;
  /** previous chord notes, used to keep the voicing close to the last one */
  previous?: number[];
};

export function modeSteps(id: ModeId): number[] {
  return MODES.find((m) => m.id === id)?.steps ?? MODES[0]!.steps;
}

export function scaleNoteNames(rootPc: number, mode: ModeId): string[] {
  return scaleDegreeNames(rootPc, modeSteps(mode), 8);
}

function classify(third: number, fifth: number): ChordQuality {
  if (third !== 3 && third !== 4) return "sus";
  if (fifth === 6) return "dim";
  if (fifth === 8) return "aug";
  return third === 3 ? "minor" : "major";
}

function suffixOf(quality: ChordQuality): string {
  switch (quality) {
    case "minor":
      return "m";
    case "dim":
      return "dim";
    case "aug":
      return "aug";
    case "sus":
      return "sus";
    default:
      return "";
  }
}

/** Stacked thirds of the mode, measured from the chord root. */
export function chordIntervals(steps: number[], degree: number) {
  const root = degreeToSemitones(steps, degree);
  return {
    third: degreeToSemitones(steps, degree + 2) - root,
    fifth: degreeToSemitones(steps, degree + 4) - root,
    seventh: degreeToSemitones(steps, degree + 6) - root,
    rootSemitones: root,
  };
}

/** Re-centres the voicing near the previous chord (simple voice leading). */
function leadVoices(notes: number[], previous?: number[]): number[] {
  if (!previous?.length) return notes;
  const centre = (list: number[]) => list.reduce((sum, n) => sum + n, 0) / list.length;
  const drift = centre(notes) - centre(previous);
  if (drift > 7) return notes.map((n) => n - 12);
  if (drift < -7) return notes.map((n) => n + 12);
  return notes;
}

export function buildChord(req: ChordRequest): Chord {
  const steps = modeSteps(req.mode);
  const octave = req.octave ?? 3;
  const tonicMidi = 12 * (octave + 1) + req.rootPc;
  const { third: diatonicThird, fifth: diatonicFifth, seventh, rootSemitones } = chordIntervals(
    steps,
    req.degree,
  );

  let third = diatonicThird;
  let fifth = diatonicFifth;
  if (req.tonality === "major") third = 4;
  if (req.tonality === "minor") third = 3;
  if (req.tonality !== "auto" && fifth === 6) fifth = 7;

  const rootMidi = tonicMidi + rootSemitones;
  const withSeventh = req.voicing === "seventh";

  let notes: number[];
  switch (req.voicing) {
    case "inv1":
      notes = [rootMidi + third, rootMidi + fifth, rootMidi + 12];
      break;
    case "inv2":
      notes = [rootMidi + fifth, rootMidi + 12, rootMidi + third + 12];
      break;
    case "open":
      notes = [rootMidi - 12, rootMidi + fifth, rootMidi + third + 12, rootMidi + seventh + 12];
      break;
    case "seventh":
      notes = [rootMidi, rootMidi + third, rootMidi + fifth, rootMidi + seventh];
      break;
    default:
      notes = [rootMidi, rootMidi + third, rootMidi + fifth];
  }

  notes = leadVoices(notes, req.previous);
  const unique = [...new Set(notes)].sort((a, b) => a - b);
  const quality = classify(third, fifth);
  const rootName = pitchClassName(rootMidi);

  return {
    degree: req.degree,
    rootMidi,
    rootName,
    quality,
    seventh: withSeventh,
    notes: unique,
    label: `${rootName}${suffixOf(quality)}${withSeventh ? "7" : ""}`,
  };
}

export function chordFrequencies(chord: Chord): number[] {
  return chord.notes.map(noteToFrequency);
}

/** UI helpers kept under the theory layer so components never touch pitch maths. */
export const midiName = noteLabel;
export const midiToFreq = noteToFrequency;
